const cool_objects = [
    {
        "name": "Andromeda Galaxy",
        "img": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Andromeda_Galaxy_%28with_h-alpha%29.jpg/1280px-Andromeda_Galaxy_%28with_h-alpha%29.jpg",
        "desc": "The Andromeda Galaxy, also known as Messier 31, is a neighbor galaxy of the Milky Way. The galaxy was discovered more than a thousand years ago, and it has over a trillion stars. It is on a collision course with our Milky Way, and the two galaxies are expected to collide in around 5 billion years.",
        "dist": 2540000.0,
        "type": "Barred Spiral Galaxy",
        "ra": 10.684708,
        "dec": 41.268750,
    },
    {
        "name": "Proxima Centauri",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Artist%27s_impression_of_the_planet_orbiting_Proxima_Centauri.jpg/1280px-Artist%27s_impression_of_the_planet_orbiting_Proxima_Centauri.jpg",
        "desc":"The closest star to our Solar System. It is a red dwarf, a star much smaller and longer-lasting than our Sun. The star has one planet in its habitable zone, and is part of a triple-star system with Alpha Centauri A and B.",
        "dist":4.2465,
        "type":"Red Dwarf Star",
        "ra":217.4289422216058,
        "dec":-62.6794901890756,
    },
    {
        "name":"Crab Nebula",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Crab_Nebula.jpg/1024px-Crab_Nebula.jpg",
        "desc":"Also known as Messier 1. A nebula that is the remains of a Supernova which was observed on Earth in 1054 CE. At the center of the nebula is a pulsar, a rapidly spinning core of a dead star. Looks amazing in x-ray!",
        "dist":6500.0,
        "type":"Supernova Remnant",
        "ra":83.6287,
        "dec":22.0147,
    },
    {
        "name":"Hoag's Object",
        "img":"https://upload.wikimedia.org/wikipedia/commons/d/da/Hoag%27s_object.jpg",
        "desc":"A very unusual type of galaxy known as a ring galaxy. On the outside are young and bright stars, with an older core. Another ring galaxy can be seen behind Hoag's Object.",
        "dist":612800000.0,
        "type":"Ring Galaxy",
        "ra":229.3100286078100,
        "dec":21.5855156265700,
    },
    {
        "name":"Sirius",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Sirius.jpg/1024px-Sirius.jpg",
        "desc":"The brightest star in the night sky. It is around twice the size of the Sun, and less than a billion years old. In the same system is Sirius B, a dead white dwarf, much dimmer than Sirius A.",
        "dist":8.60,
        "type":"Binary System",
        "ra":101.28715533,
        "dec":-16.71611586,
    },
    {
        "name":"Horsehead Nebula",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Barnard_33.jpg/1042px-Barnard_33.jpg",
        "desc":"A nebula with the shape of a horse's head. It is made up of interstellar gas as a part of a bigger cloud. The reddish color around the nebula is caused by a nearby star energizing gas.",
        "dist":1375.0,
        "type":"Dark Nebula",
        "ra":85.2458,
        "dec":-2.4583,
    },
    {
        "name":"Mice Galaxies",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Merging_galaxies_NGC_4676_%28captured_by_the_Hubble_Space_Telescope%29.jpg/1024px-Merging_galaxies_NGC_4676_%28captured_by_the_Hubble_Space_Telescope%29.jpg",
        "desc":`Two galaxies which are merging with each other. Large "tails" of stars can be seen on both galaxies, caused by difference in gravity due to distance, similar to tides on Earth.`,
        "dist":290000000.0,
        "type":"Merging Galaxies",
        "ra":191.54242,
        "dec":30.73158,
    },
    {
        "name":"The Pleaides",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pleiades_large.jpg/1280px-Pleiades_large.jpg",
        "desc":`A bright star cluster very close to Earth. The cluster is mostly made up of very bright, blue, and young stars. In 250 million years, the stars in the Pleiades will scatter due to disturbances from nearby objects.`,
        "dist":444.0,
        "type":"Open Star Cluster",
        "ra":56.6010,
        "dec":24.1140,
    },
    {
        "name":"Pillars of Creation",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Pillars_of_creation_2014_HST_WFC3-UVIS_full-res_denoised.jpg/1964px-Pillars_of_creation_2014_HST_WFC3-UVIS_full-res_denoised.jpg",
        "desc":`Three large pillars of gas in the Eagle Nebula. The largest one is 4 light years tall. The Pillars of Creation are named because they're regions of intense star formation. It's possible the pillars have been destroyed by a supernova, but the light from such an event would take 7,000 years to reach us.`,
        "dist":7000.0,
        "type":"Nebula Formation",
        "ra":274.6880,
        "dec":-13.7920,
    },
    {
        "name":"Galactic Center",
        "img":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Galactic_Center_%28Chandra%2C_Hubble%2C_Spitzer%29_%282021-053-01FJHQEC71T0CF7KTRGDYAKBYJ%29.png/1280px-Galactic_Center_%28Chandra%2C_Hubble%2C_Spitzer%29_%282021-053-01FJHQEC71T0CF7KTRGDYAKBYJ%29.png",
        "desc":`At the center of our Milky Way Galaxy is a supermassive black hole known as Sagittarius A. This black hole has the mass of millions of suns, and has millions of stars and a lot of interstellar dust orbiting it. It can be seen clearly in x-ray view.`,
        "dist":26670,
        "type":"Supermassive Black Hole",
        "ra":266.41681662,
        "dec":-29.00782497,
    },
]

export {cool_objects}